spring.application.name=task-api
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=la vnl mon but
spring.jpa.hibernate.ddl-auto=none